#!/usr/bin/env bash
# Summary: Display prefix for an istioctl version
# Usage: istioctlenv prefix [<version>]
#
# Displays the directory where an istioctl version is installed. If no
# version is given, `istioctlenv prefix' displays the location of the
# currently selected version.

set -e
[ -n "$ISTIOCTLENV_DEBUG" ] && set -x

# Provide istioctlenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec istioctlenv-versions --bare
fi

if [ -n "$1" ]; then
  OLDIFS="$IFS"
  {
    IFS=:
    export ISTIOCTLENV_VERSION="$*"
  }
  IFS="$OLDIFS"
elif [ -z "$ISTIOCTLENV_VERSION" ]; then
  ISTIOCTLENV_VERSION="$(istioctlenv-version-name)"
fi

ISTIOCTLENV_PREFIX_PATHS=()
OLDIFS="$IFS"
{
  IFS=:
  for version in ${ISTIOCTLENV_VERSION}; do
    if [ "$version" = "system" ]; then
      if ISTIOCTL_PATH="$(ISTIOCTLENV_VERSION="${version}" istioctlenv-which istioctl 2>/dev/null)"; then
        ISTIOCTLENV_PREFIX_PATH="${ISTIOCTL_PATH%/istioctl}"
      else
        echo "istioctlenv: system version not found in PATH" >&2
        exit 1
      fi
    else
      ISTIOCTLENV_PREFIX_PATH="${ISTIOCTLENV_ROOT}/versions/${version}"
    fi
    if [ -d "$ISTIOCTLENV_PREFIX_PATH" ]; then
      ISTIOCTLENV_PREFIX_PATHS=("${ISTIOCTLENV_PREFIX_PATHS[@]}" "$ISTIOCTLENV_PREFIX_PATH")
    else
      echo "istioctlenv: version '${version}' not installed" >&2
      exit 1
    fi
  done
}
IFS="$OLDIFS"

OLDIFS="$IFS"
{
  IFS=:
  echo "${ISTIOCTLENV_PREFIX_PATHS[*]}"
}
IFS="$OLDIFS"
