#!/usr/bin/env bash
# Usage: istioctlenv completions <command> [arg1 arg2...]
# Summary: Provides auto-completion for itself and other commands by calling them with `--complete`.

set -e
[ -n "$ISTIOCTLENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  istioctlenv-help --usage completions >&2
  exit 1
fi

# Provide istioctlenv completions
if [ "$COMMAND" = "--complete" ]; then
  exec istioctlenv-commands
fi

COMMAND_PATH="$(command -v "istioctlenv-$COMMAND" || command -v "istioctlenv-sh-$COMMAND")"

# --help is provided automatically
echo --help

if grep -iE "^([#%]|--|//) provide istioctlenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
