#!/usr/bin/env bash
#
# Summary: Set or show the global istioctl version
#
# Usage: istioctlenv global <version>
#
# Sets the global istioctl version. You can override the global version at
# any time by setting a directory-specific version with `istioctlenv local'
# or by setting the `ISTIOCTLENV_VERSION' environment variable.
#
# <version> should be a string matching a istioctl version known to istioctlenv.
# The special version string `system' will use your default system istioctl.
# Run `istioctlenv versions' for a list of available istioctl versions.

set -e
[ -n "$ISTIOCTLENV_DEBUG" ] && set -x

# Provide istioctlenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec istioctlenv-versions --bare
fi

versions=("$@")
ISTIOCTLENV_VERSION_FILE="${ISTIOCTLENV_ROOT}/version"

if [ -n "$versions" ]; then
  istioctlenv-version-file-write "$ISTIOCTLENV_VERSION_FILE" "${versions[@]}"
else
  OLDIFS="$IFS"
  IFS=: versions=($(
    istioctlenv-version-file-read "$ISTIOCTLENV_VERSION_FILE" ||
    istioctlenv-version-file-read "${ISTIOCTLENV_ROOT}/global" ||
    istioctlenv-version-file-read "${ISTIOCTLENV_ROOT}/default" ||
    echo system
  ))
  IFS="$OLDIFS"
  for version in "${versions[@]}"; do
    echo "$version"
  done
fi
