#!/usr/bin/env bash
# Summary: Display the version
#
# Displays the version number of this release

set -e
[ -n "$ISTIOCTLENV_DEBUG" ] && set -x

SCRIPT_DIR=$(cd $(dirname $0); pwd)
ROOT_DIR=${SCRIPT_DIR}/..

version=$(cat ${ROOT_DIR}/VERSION)

echo "istioctlenv ${version}"
