#!/usr/bin/env bash
# Summary: Show the current istioctl version and its origin
#
# Usage: istioctlenv version
#
# Shows the currently selected istioctl version and how it was
# selected. To obtain only the version string, use `istioctlenv version-name'.

set -e
[ -n "$ISTIOCTLENV_DEBUG" ] && set -x

exitcode=0
OLDIFS="$IFS"
IFS=: ISTIOCTLENV_VERSION_NAMES=($(istioctlenv-version-name)) || exitcode=$?
IFS="$OLDIFS"

for ISTIOCTLENV_VERSION_NAME in "${ISTIOCTLENV_VERSION_NAMES[@]}"; do
  echo "$ISTIOCTLENV_VERSION_NAME (set by $(istioctlenv-version-origin))"
done

exit $exitcode
