#!/usr/bin/env bash
# Summary: Calls `istioctlenv-rehash` to rehash shims and rehashes shell executable if shell is not 'fish'.
# Usage: istioctlenv sh-rehash [--only-manage-paths]

set -e
[ -n "$ISTIOCTLENV_DEBUG" ] && set -x

# Provide istioctlenv completions
if [ "$1" = "--complete" ]; then
  exec istioctlenv-rehash --complete
fi

shell="$(basename "${ISTIOCTLENV_SHELL:-$SHELL}")"

# NOTE: When istioctlenv shell integration is enabled, delegate rehashing of `istioctlenv` shims to istioctlenv-rehash.
# However to speed up `istioctlenv init` and not do rehashing of shims twice,
# allow `only-manage-paths` to skip rehashing of shims.
if [ "$1" != "--only-manage-paths" ]; then
  istioctlenv-rehash
fi
